### ISSUE TITLE
Error #1006

### ISSUE THREAD

**Issue by yeldarby** [arkeus/as3-controller-input#2]
First off, thanks for posting this code. It's working much better than the other libraries I found.

I'm not sure what's going on but the following works correctly yet traces out "Error Error #1006"

```
try {
    keyState.left   = ouyaController.dpad.left.pressed()    || ouyaController.dpad.left.held()  || ouyaController.leftStick.left.pressed()  || ouyaController.leftStick.left.held();
    keyState.right  = ouyaController.dpad.right.pressed()   || ouyaController.dpad.right.held() || ouyaController.leftStick.right.pressed() || ouyaController.leftStick.right.held();
    keyState.up     = ouyaController.dpad.up.pressed()      || ouyaController.dpad.up.held()    || ouyaController.leftStick.up.pressed()    || ouyaController.leftStick.up.held();
    keyState.down   = ouyaController.dpad.down.pressed()    || ouyaController.dpad.down.held()  || ouyaController.leftStick.down.pressed()  || ouyaController.leftStick.down.held();
} catch(e) {
    trace('Error ' + e.message + "\n");
}
```

Google seems to suggest that "Error #1006" means "not a function". I had a glance through the soure code and I believe these all should be callable functions (and it works).

Any ideas?

**Comment by arkeus** [comment]
All the attributes of each button (held, pressed) are getters, so you shouldn't be calling them as functions, but should be accessing them as variables. I think just taking off the () from each of those should fix it.

**Comment by yeldarby** [comment]
Ah that'd do it, thanks. My ActionScript is pretty rusty.
